[web]
port = "8080"

mode = "debug"

[log]
level = "info"
path = "/var/log/app.log"

[dataSource]
[dataSource.dataBase]
dsn = "user:password@tcp(localhost:3306)/dbname?charset=utf8mb4&parseTime=True&loc=Local"

[dataSource.redis]
dsn = "localhost:6379"
